/* automatically generated by rust-bindgen 0.72.1 */

// Generated by tools/regen-bindings.sh. Do not edit by hand.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

pub const LIBUSB20_MAX_FRAME_PRE_SCALE: u32 = 2147483648;
#[doc = " Success (no error)"]
pub const libusb20_error_LIBUSB20_SUCCESS: libusb20_error = 0;
#[doc = " Input/output error"]
pub const libusb20_error_LIBUSB20_ERROR_IO: libusb20_error = -1;
#[doc = " Invalid parameter"]
pub const libusb20_error_LIBUSB20_ERROR_INVALID_PARAM: libusb20_error = -2;
#[doc = " Access denied (insufficient permissions)"]
pub const libusb20_error_LIBUSB20_ERROR_ACCESS: libusb20_error = -3;
#[doc = " No such device (it may have been disconnected)"]
pub const libusb20_error_LIBUSB20_ERROR_NO_DEVICE: libusb20_error = -4;
#[doc = " Entity not found"]
pub const libusb20_error_LIBUSB20_ERROR_NOT_FOUND: libusb20_error = -5;
#[doc = " Resource busy"]
pub const libusb20_error_LIBUSB20_ERROR_BUSY: libusb20_error = -6;
#[doc = " Operation timed out"]
pub const libusb20_error_LIBUSB20_ERROR_TIMEOUT: libusb20_error = -7;
#[doc = " Overflow"]
pub const libusb20_error_LIBUSB20_ERROR_OVERFLOW: libusb20_error = -8;
#[doc = " Pipe error"]
pub const libusb20_error_LIBUSB20_ERROR_PIPE: libusb20_error = -9;
#[doc = " System call interrupted (perhaps due to signal)"]
pub const libusb20_error_LIBUSB20_ERROR_INTERRUPTED: libusb20_error = -10;
#[doc = " Insufficient memory"]
pub const libusb20_error_LIBUSB20_ERROR_NO_MEM: libusb20_error = -11;
#[doc = " Operation not supported or unimplemented on this platform"]
pub const libusb20_error_LIBUSB20_ERROR_NOT_SUPPORTED: libusb20_error = -12;
#[doc = " Other error"]
pub const libusb20_error_LIBUSB20_ERROR_OTHER: libusb20_error = -99;
#[doc = " \\ingroup misc\n Error codes. Most libusb20 functions return 0 on success or one of\n these codes on failure."]
pub type libusb20_error = ::std::os::raw::c_int;
#[doc = " Transfer completed without error. Note that this does not\n indicate that the entire amount of requested data was\n transferred."]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_COMPLETED: libusb20_transfer_status = 0;
#[doc = " Callback code to start transfer"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_START: libusb20_transfer_status = 1;
#[doc = " Drain complete callback code"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_DRAINED: libusb20_transfer_status = 2;
#[doc = " Transfer failed"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_ERROR: libusb20_transfer_status = 3;
#[doc = " Transfer timed out"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_TIMED_OUT: libusb20_transfer_status = 4;
#[doc = " Transfer was cancelled"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_CANCELLED: libusb20_transfer_status = 5;
#[doc = " For bulk/interrupt endpoints: halt condition detected\n (endpoint stalled). For control endpoints: control request\n not supported."]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_STALL: libusb20_transfer_status = 6;
#[doc = " Device was disconnected"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_NO_DEVICE: libusb20_transfer_status = 7;
#[doc = " Device sent more data than requested"]
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_OVERFLOW: libusb20_transfer_status = 8;
#[doc = " \\ingroup asyncio\n libusb20_tr_get_status() values"]
pub type libusb20_transfer_status = ::std::os::raw::c_uint;
#[doc = " Report a short frame as error"]
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_SINGLE_SHORT_NOT_OK: libusb20_transfer_flags =
    1;
#[doc = " Multiple short frames are not allowed"]
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_MULTI_SHORT_NOT_OK: libusb20_transfer_flags = 2;
#[doc = " All transmitted frames are short terminated"]
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_FORCE_SHORT: libusb20_transfer_flags = 4;
#[doc = " Will do a clear-stall before xfer"]
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_DO_CLEAR_STALL: libusb20_transfer_flags = 8;
#[doc = " \\ingroup asyncio\n libusb20_tr_set_flags() values"]
pub type libusb20_transfer_flags = ::std::os::raw::c_uint;
pub const libusb20_device_mode_LIBUSB20_MODE_HOST: libusb20_device_mode = 0;
pub const libusb20_device_mode_LIBUSB20_MODE_DEVICE: libusb20_device_mode = 1;
#[doc = " \\ingroup misc\n libusb20_dev_get_mode() values"]
pub type libusb20_device_mode = ::std::os::raw::c_uint;
pub const LIBUSB20_SPEED_UNKNOWN: _bindgen_ty_1 = 0;
pub const LIBUSB20_SPEED_LOW: _bindgen_ty_1 = 1;
pub const LIBUSB20_SPEED_FULL: _bindgen_ty_1 = 2;
pub const LIBUSB20_SPEED_HIGH: _bindgen_ty_1 = 3;
pub const LIBUSB20_SPEED_VARIABLE: _bindgen_ty_1 = 4;
pub const LIBUSB20_SPEED_SUPER: _bindgen_ty_1 = 5;
pub const LIBUSB20_SPEED_SUPER_PLUS: _bindgen_ty_1 = 6;
#[doc = " \\ingroup misc\n libusb20_dev_get_speed() values"]
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub const LIBUSB20_POWER_OFF: _bindgen_ty_2 = 0;
pub const LIBUSB20_POWER_ON: _bindgen_ty_2 = 1;
pub const LIBUSB20_POWER_SAVE: _bindgen_ty_2 = 2;
pub const LIBUSB20_POWER_SUSPEND: _bindgen_ty_2 = 3;
pub const LIBUSB20_POWER_RESUME: _bindgen_ty_2 = 4;
#[doc = " \\ingroup misc\n libusb20_dev_set_power() values"]
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct usb_device_info {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_transfer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_backend {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_backend_methods {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_device {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_device_methods {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_config {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_CONTROL_SETUP_DECODED {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_DEVICE_DESC_DECODED {
    _unused: [u8; 0],
}
pub type libusb20_tr_callback_t =
    ::std::option::Option<unsafe extern "C" fn(xfer: *mut libusb20_transfer)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_quirk {
    pub vid: u16,
    pub pid: u16,
    pub bcdDeviceLow: u16,
    pub bcdDeviceHigh: u16,
    pub reserved: [u16; 2usize],
    pub quirkname: [::std::os::raw::c_char; 52usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_device_stats {
    pub xfer_ok: [u64; 4usize],
    pub xfer_fail: [u64; 4usize],
    pub xfer_reserved: [u64; 24usize],
}
unsafe extern "C" {
    pub fn libusb20_tr_close(xfer: *mut libusb20_transfer) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_tr_open(
        xfer: *mut libusb20_transfer,
        max_buf_size: u32,
        max_frame_count: u32,
        ep_no: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_tr_open_stream(
        xfer: *mut libusb20_transfer,
        max_buf_size: u32,
        max_frame_count: u32,
        ep_no: u8,
        stream_id: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_pointer(
        pdev: *mut libusb20_device,
        tr_index: u16,
    ) -> *mut libusb20_transfer;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_time_complete(xfer: *mut libusb20_transfer) -> u16;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_actual_frames(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_actual_length(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_max_frames(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_max_packet_length(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_max_total_length(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_status(xfer: *mut libusb20_transfer) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_tr_pending(xfer: *mut libusb20_transfer) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_tr_callback_wrapper(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_clear_stall_sync(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_drain(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_buffer(
        xfer: *mut libusb20_transfer,
        buffer: *mut ::std::os::raw::c_void,
        fr_index: u16,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_set_callback(xfer: *mut libusb20_transfer, cb: libusb20_tr_callback_t);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_flags(xfer: *mut libusb20_transfer, flags: u8);
}
unsafe extern "C" {
    pub fn libusb20_tr_get_length(xfer: *mut libusb20_transfer, fr_index: u16) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_set_length(xfer: *mut libusb20_transfer, length: u32, fr_index: u16);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_priv_sc0(xfer: *mut libusb20_transfer, sc0: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_priv_sc1(xfer: *mut libusb20_transfer, sc1: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_timeout(xfer: *mut libusb20_transfer, timeout: u32);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_total_frames(xfer: *mut libusb20_transfer, nFrames: u32);
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_bulk(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        timeout: u32,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_control(
        xfer: *mut libusb20_transfer,
        psetup: *mut ::std::os::raw::c_void,
        pbuf: *mut ::std::os::raw::c_void,
        timeout: u32,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_intr(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        timeout: u32,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_isoc(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        fr_index: u16,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_bulk_intr_sync(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        pactlen: *mut u32,
        timeout: u32,
    ) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_tr_start(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_stop(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_submit(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_get_priv_sc0(xfer: *mut libusb20_transfer) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_priv_sc1(xfer: *mut libusb20_transfer) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_backend_name(
        pdev: *mut libusb20_device,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_desc(pdev: *mut libusb20_device) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn libusb20_dev_close(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_detach_kernel_driver(
        pdev: *mut libusb20_device,
        iface_index: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_set_config_index(
        pdev: *mut libusb20_device,
        configIndex: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_debug(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_fd(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_stats(
        pdev: *mut libusb20_device,
        pstat: *mut libusb20_device_stats,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_kernel_driver_active(
        pdev: *mut libusb20_device,
        iface_index: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_open(
        pdev: *mut libusb20_device,
        transfer_max: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_process(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_request_sync(
        pdev: *mut libusb20_device,
        setup: *mut LIBUSB20_CONTROL_SETUP_DECODED,
        data: *mut ::std::os::raw::c_void,
        pactlen: *mut u16,
        timeout: u32,
        flags: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_req_string_sync(
        pdev: *mut libusb20_device,
        index: u8,
        langid: u16,
        ptr: *mut ::std::os::raw::c_void,
        len: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_req_string_simple_sync(
        pdev: *mut libusb20_device,
        index: u8,
        ptr: *mut ::std::os::raw::c_void,
        len: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_reset(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_check_connected(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_set_power_mode(
        pdev: *mut libusb20_device,
        power_mode: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_power_mode(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_port_path(
        pdev: *mut libusb20_device,
        buf: *mut u8,
        bufsize: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_power_usage(pdev: *mut libusb20_device) -> u16;
}
unsafe extern "C" {
    pub fn libusb20_dev_set_alt_index(
        pdev: *mut libusb20_device,
        iface_index: u8,
        alt_index: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_info(
        pdev: *mut libusb20_device,
        pinfo: *mut usb_device_info,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_iface_desc(
        pdev: *mut libusb20_device,
        iface_index: u8,
        buf: *mut ::std::os::raw::c_char,
        len: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_device_desc(
        pdev: *mut libusb20_device,
    ) -> *mut LIBUSB20_DEVICE_DESC_DECODED;
}
unsafe extern "C" {
    pub fn libusb20_dev_alloc_config(
        pdev: *mut libusb20_device,
        config_index: u8,
    ) -> *mut libusb20_config;
}
unsafe extern "C" {
    pub fn libusb20_dev_alloc() -> *mut libusb20_device;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_address(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_parent_address(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_parent_port(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_bus_number(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_mode(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_speed(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_config_index(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_free(pdev: *mut libusb20_device);
}
unsafe extern "C" {
    pub fn libusb20_dev_set_debug(pdev: *mut libusb20_device, debug: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn libusb20_dev_wait_process(pdev: *mut libusb20_device, timeout: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn libusb20_be_get_dev_quirk(
        pbe: *mut libusb20_backend,
        index: u16,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_get_quirk_name(
        pbe: *mut libusb20_backend,
        index: u16,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_add_dev_quirk(
        pbe: *mut libusb20_backend,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_remove_dev_quirk(
        pbe: *mut libusb20_backend,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_get_template(
        pbe: *mut libusb20_backend,
        ptemp: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_set_template(
        pbe: *mut libusb20_backend,
        temp: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc(methods: *const libusb20_backend_methods) -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_default() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_freebsd() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_linux() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_ugen20() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_device_foreach(
        pbe: *mut libusb20_backend,
        pdev: *mut libusb20_device,
    ) -> *mut libusb20_device;
}
unsafe extern "C" {
    pub fn libusb20_be_dequeue_device(pbe: *mut libusb20_backend, pdev: *mut libusb20_device);
}
unsafe extern "C" {
    pub fn libusb20_be_enqueue_device(pbe: *mut libusb20_backend, pdev: *mut libusb20_device);
}
unsafe extern "C" {
    pub fn libusb20_be_free(pbe: *mut libusb20_backend);
}
