/* automatically generated by rust-bindgen 0.72.1 */

// Generated by tools/regen-bindings.sh. Do not edit by hand.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

pub const LIBUSB20_MAX_FRAME_PRE_SCALE: u32 = 2147483648;
pub const LIBUSB20_DT_DEVICE_SIZE: u32 = 18;
pub const LIBUSB20_DT_CONFIG_SIZE: u32 = 9;
pub const LIBUSB20_DT_INTERFACE_SIZE: u32 = 9;
pub const LIBUSB20_DT_ENDPOINT_SIZE: u32 = 7;
pub const LIBUSB20_DT_ENDPOINT_AUDIO_SIZE: u32 = 9;
pub const LIBUSB20_DT_HUB_NONVAR_SIZE: u32 = 7;
pub const LIBUSB20_DT_SS_ENDPOINT_COMPANION_SIZE: u32 = 6;
pub const LIBUSB20_DT_BOS_SIZE: u32 = 5;
pub const LIBUSB20_USB_2_0_EXTENSION_DEVICE_CAPABILITY_SIZE: u32 = 7;
pub const LIBUSB20_SS_USB_DEVICE_CAPABILITY_SIZE: u32 = 10;
pub const LIBUSB20_ENDPOINT_ADDRESS_MASK: u32 = 15;
pub const LIBUSB20_ENDPOINT_DIR_MASK: u32 = 128;
pub const LIBUSB20_TRANSFER_TYPE_MASK: u32 = 3;
pub const LIBUSB20_ISO_SYNC_TYPE_MASK: u32 = 12;
pub const LIBUSB20_ISO_USAGE_TYPE_MASK: u32 = 48;
pub const libusb20_error_LIBUSB20_SUCCESS: libusb20_error = 0;
pub const libusb20_error_LIBUSB20_ERROR_IO: libusb20_error = -1;
pub const libusb20_error_LIBUSB20_ERROR_INVALID_PARAM: libusb20_error = -2;
pub const libusb20_error_LIBUSB20_ERROR_ACCESS: libusb20_error = -3;
pub const libusb20_error_LIBUSB20_ERROR_NO_DEVICE: libusb20_error = -4;
pub const libusb20_error_LIBUSB20_ERROR_NOT_FOUND: libusb20_error = -5;
pub const libusb20_error_LIBUSB20_ERROR_BUSY: libusb20_error = -6;
pub const libusb20_error_LIBUSB20_ERROR_TIMEOUT: libusb20_error = -7;
pub const libusb20_error_LIBUSB20_ERROR_OVERFLOW: libusb20_error = -8;
pub const libusb20_error_LIBUSB20_ERROR_PIPE: libusb20_error = -9;
pub const libusb20_error_LIBUSB20_ERROR_INTERRUPTED: libusb20_error = -10;
pub const libusb20_error_LIBUSB20_ERROR_NO_MEM: libusb20_error = -11;
pub const libusb20_error_LIBUSB20_ERROR_NOT_SUPPORTED: libusb20_error = -12;
pub const libusb20_error_LIBUSB20_ERROR_OTHER: libusb20_error = -99;
pub type libusb20_error = ::std::os::raw::c_int;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_COMPLETED: libusb20_transfer_status = 0;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_START: libusb20_transfer_status = 1;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_DRAINED: libusb20_transfer_status = 2;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_ERROR: libusb20_transfer_status = 3;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_TIMED_OUT: libusb20_transfer_status = 4;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_CANCELLED: libusb20_transfer_status = 5;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_STALL: libusb20_transfer_status = 6;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_NO_DEVICE: libusb20_transfer_status = 7;
pub const libusb20_transfer_status_LIBUSB20_TRANSFER_OVERFLOW: libusb20_transfer_status = 8;
pub type libusb20_transfer_status = ::std::os::raw::c_uint;
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_SINGLE_SHORT_NOT_OK: libusb20_transfer_flags =
    1;
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_MULTI_SHORT_NOT_OK: libusb20_transfer_flags = 2;
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_FORCE_SHORT: libusb20_transfer_flags = 4;
pub const libusb20_transfer_flags_LIBUSB20_TRANSFER_DO_CLEAR_STALL: libusb20_transfer_flags = 8;
pub type libusb20_transfer_flags = ::std::os::raw::c_uint;
pub const libusb20_device_mode_LIBUSB20_MODE_HOST: libusb20_device_mode = 0;
pub const libusb20_device_mode_LIBUSB20_MODE_DEVICE: libusb20_device_mode = 1;
pub type libusb20_device_mode = ::std::os::raw::c_uint;
pub const LIBUSB20_SPEED_UNKNOWN: _bindgen_ty_1 = 0;
pub const LIBUSB20_SPEED_LOW: _bindgen_ty_1 = 1;
pub const LIBUSB20_SPEED_FULL: _bindgen_ty_1 = 2;
pub const LIBUSB20_SPEED_HIGH: _bindgen_ty_1 = 3;
pub const LIBUSB20_SPEED_VARIABLE: _bindgen_ty_1 = 4;
pub const LIBUSB20_SPEED_SUPER: _bindgen_ty_1 = 5;
pub const LIBUSB20_SPEED_SUPER_PLUS: _bindgen_ty_1 = 6;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub const LIBUSB20_POWER_OFF: _bindgen_ty_2 = 0;
pub const LIBUSB20_POWER_ON: _bindgen_ty_2 = 1;
pub const LIBUSB20_POWER_SAVE: _bindgen_ty_2 = 2;
pub const LIBUSB20_POWER_SUSPEND: _bindgen_ty_2 = 3;
pub const LIBUSB20_POWER_RESUME: _bindgen_ty_2 = 4;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct usb_device_info {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_transfer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_backend {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_backend_methods {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_device {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_device_methods {
    _unused: [u8; 0],
}
pub type libusb20_tr_callback_t =
    ::std::option::Option<unsafe extern "C" fn(xfer: *mut libusb20_transfer)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_quirk {
    pub vid: u16,
    pub pid: u16,
    pub bcdDeviceLow: u16,
    pub bcdDeviceHigh: u16,
    pub reserved: [u16; 2usize],
    pub quirkname: [::std::os::raw::c_char; 52usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_device_stats {
    pub xfer_ok: [u64; 4usize],
    pub xfer_fail: [u64; 4usize],
    pub xfer_reserved: [u64; 24usize],
}
unsafe extern "C" {
    pub fn libusb20_tr_close(xfer: *mut libusb20_transfer) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_tr_open(
        xfer: *mut libusb20_transfer,
        max_buf_size: u32,
        max_frame_count: u32,
        ep_no: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_tr_open_stream(
        xfer: *mut libusb20_transfer,
        max_buf_size: u32,
        max_frame_count: u32,
        ep_no: u8,
        stream_id: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_pointer(
        pdev: *mut libusb20_device,
        tr_index: u16,
    ) -> *mut libusb20_transfer;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_time_complete(xfer: *mut libusb20_transfer) -> u16;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_actual_frames(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_actual_length(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_max_frames(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_max_packet_length(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_max_total_length(xfer: *mut libusb20_transfer) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_status(xfer: *mut libusb20_transfer) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_tr_pending(xfer: *mut libusb20_transfer) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_tr_callback_wrapper(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_clear_stall_sync(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_drain(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_buffer(
        xfer: *mut libusb20_transfer,
        buffer: *mut ::std::os::raw::c_void,
        fr_index: u16,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_set_callback(xfer: *mut libusb20_transfer, cb: libusb20_tr_callback_t);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_flags(xfer: *mut libusb20_transfer, flags: u8);
}
unsafe extern "C" {
    pub fn libusb20_tr_get_length(xfer: *mut libusb20_transfer, fr_index: u16) -> u32;
}
unsafe extern "C" {
    pub fn libusb20_tr_set_length(xfer: *mut libusb20_transfer, length: u32, fr_index: u16);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_priv_sc0(xfer: *mut libusb20_transfer, sc0: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_priv_sc1(xfer: *mut libusb20_transfer, sc1: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_timeout(xfer: *mut libusb20_transfer, timeout: u32);
}
unsafe extern "C" {
    pub fn libusb20_tr_set_total_frames(xfer: *mut libusb20_transfer, nFrames: u32);
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_bulk(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        timeout: u32,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_control(
        xfer: *mut libusb20_transfer,
        psetup: *mut ::std::os::raw::c_void,
        pbuf: *mut ::std::os::raw::c_void,
        timeout: u32,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_intr(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        timeout: u32,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_setup_isoc(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        fr_index: u16,
    );
}
unsafe extern "C" {
    pub fn libusb20_tr_bulk_intr_sync(
        xfer: *mut libusb20_transfer,
        pbuf: *mut ::std::os::raw::c_void,
        length: u32,
        pactlen: *mut u32,
        timeout: u32,
    ) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_tr_start(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_stop(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_submit(xfer: *mut libusb20_transfer);
}
unsafe extern "C" {
    pub fn libusb20_tr_get_priv_sc0(xfer: *mut libusb20_transfer) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn libusb20_tr_get_priv_sc1(xfer: *mut libusb20_transfer) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_backend_name(
        pdev: *mut libusb20_device,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_desc(pdev: *mut libusb20_device) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn libusb20_dev_close(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_detach_kernel_driver(
        pdev: *mut libusb20_device,
        iface_index: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_set_config_index(
        pdev: *mut libusb20_device,
        configIndex: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_debug(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_fd(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_stats(
        pdev: *mut libusb20_device,
        pstat: *mut libusb20_device_stats,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_kernel_driver_active(
        pdev: *mut libusb20_device,
        iface_index: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_open(
        pdev: *mut libusb20_device,
        transfer_max: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_process(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_request_sync(
        pdev: *mut libusb20_device,
        setup: *mut LIBUSB20_CONTROL_SETUP_DECODED,
        data: *mut ::std::os::raw::c_void,
        pactlen: *mut u16,
        timeout: u32,
        flags: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_req_string_sync(
        pdev: *mut libusb20_device,
        index: u8,
        langid: u16,
        ptr: *mut ::std::os::raw::c_void,
        len: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_req_string_simple_sync(
        pdev: *mut libusb20_device,
        index: u8,
        ptr: *mut ::std::os::raw::c_void,
        len: u16,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_reset(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_check_connected(pdev: *mut libusb20_device) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_set_power_mode(
        pdev: *mut libusb20_device,
        power_mode: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_power_mode(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_port_path(
        pdev: *mut libusb20_device,
        buf: *mut u8,
        bufsize: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_power_usage(pdev: *mut libusb20_device) -> u16;
}
unsafe extern "C" {
    pub fn libusb20_dev_set_alt_index(
        pdev: *mut libusb20_device,
        iface_index: u8,
        alt_index: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_info(
        pdev: *mut libusb20_device,
        pinfo: *mut usb_device_info,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_iface_desc(
        pdev: *mut libusb20_device,
        iface_index: u8,
        buf: *mut ::std::os::raw::c_char,
        len: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_device_desc(
        pdev: *mut libusb20_device,
    ) -> *mut LIBUSB20_DEVICE_DESC_DECODED;
}
unsafe extern "C" {
    pub fn libusb20_dev_alloc_config(
        pdev: *mut libusb20_device,
        config_index: u8,
    ) -> *mut libusb20_config;
}
unsafe extern "C" {
    pub fn libusb20_dev_alloc() -> *mut libusb20_device;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_address(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_parent_address(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_parent_port(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_bus_number(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_mode(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_speed(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_get_config_index(pdev: *mut libusb20_device) -> u8;
}
unsafe extern "C" {
    pub fn libusb20_dev_free(pdev: *mut libusb20_device);
}
unsafe extern "C" {
    pub fn libusb20_dev_set_debug(pdev: *mut libusb20_device, debug: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn libusb20_dev_wait_process(pdev: *mut libusb20_device, timeout: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn libusb20_be_get_dev_quirk(
        pbe: *mut libusb20_backend,
        index: u16,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_get_quirk_name(
        pbe: *mut libusb20_backend,
        index: u16,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_add_dev_quirk(
        pbe: *mut libusb20_backend,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_remove_dev_quirk(
        pbe: *mut libusb20_backend,
        pq: *mut libusb20_quirk,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_get_template(
        pbe: *mut libusb20_backend,
        ptemp: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_set_template(
        pbe: *mut libusb20_backend,
        temp: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc(methods: *const libusb20_backend_methods) -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_default() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_freebsd() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_linux() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_alloc_ugen20() -> *mut libusb20_backend;
}
unsafe extern "C" {
    pub fn libusb20_be_device_foreach(
        pbe: *mut libusb20_backend,
        pdev: *mut libusb20_device,
    ) -> *mut libusb20_device;
}
unsafe extern "C" {
    pub fn libusb20_be_dequeue_device(pbe: *mut libusb20_backend, pdev: *mut libusb20_device);
}
unsafe extern "C" {
    pub fn libusb20_be_enqueue_device(pbe: *mut libusb20_backend, pdev: *mut libusb20_device);
}
unsafe extern "C" {
    pub fn libusb20_be_free(pbe: *mut libusb20_backend);
}
pub const LIBUSB20_ME_INT8: _bindgen_ty_3 = 0;
pub const LIBUSB20_ME_INT16: _bindgen_ty_3 = 1;
pub const LIBUSB20_ME_INT32: _bindgen_ty_3 = 2;
pub const LIBUSB20_ME_INT64: _bindgen_ty_3 = 3;
pub const LIBUSB20_ME_STRUCT: _bindgen_ty_3 = 4;
pub const LIBUSB20_ME_MAX: _bindgen_ty_3 = 5;
pub type _bindgen_ty_3 = ::std::os::raw::c_uint;
pub const LIBUSB20_ME_IS_UNSIGNED: _bindgen_ty_4 = 0;
pub const LIBUSB20_ME_IS_SIGNED: _bindgen_ty_4 = 128;
pub const LIBUSB20_ME_MASK: _bindgen_ty_4 = 127;
pub type _bindgen_ty_4 = ::std::os::raw::c_uint;
pub const LIBUSB20_ME_IS_RAW: _bindgen_ty_5 = 0;
pub const LIBUSB20_ME_IS_ENCODED: _bindgen_ty_5 = 1;
pub const LIBUSB20_ME_IS_EMPTY: _bindgen_ty_5 = 2;
pub const LIBUSB20_ME_IS_DECODED: _bindgen_ty_5 = 3;
pub type _bindgen_ty_5 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_me_struct {
    pub ptr: *mut ::std::os::raw::c_void,
    pub len: u16,
    pub type_: u16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_me_format {
    pub format: *const u8,
    pub desc: *const ::std::os::raw::c_char,
    pub fields: *const ::std::os::raw::c_char,
}
unsafe extern "C" {
    pub static LIBUSB20_DEVICE_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_DEVICE_DESC_DECODED {
    pub LIBUSB20_DEVICE_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub bcdUSB: u16,
    pub bDeviceClass: u8,
    pub bDeviceSubClass: u8,
    pub bDeviceProtocol: u8,
    pub bMaxPacketSize0: u8,
    pub idVendor: u16,
    pub idProduct: u16,
    pub bcdDevice: u16,
    pub iManufacturer: u8,
    pub iProduct: u8,
    pub iSerialNumber: u8,
    pub bNumConfigurations: u8,
}
unsafe extern "C" {
    pub static LIBUSB20_ENDPOINT_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_ENDPOINT_DESC_DECODED {
    pub LIBUSB20_ENDPOINT_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub bEndpointAddress: u8,
    pub bmAttributes: u8,
    pub wMaxPacketSize: u16,
    pub bInterval: u8,
    pub bRefresh: u8,
    pub bSynchAddress: u8,
}
unsafe extern "C" {
    pub static LIBUSB20_INTERFACE_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_INTERFACE_DESC_DECODED {
    pub LIBUSB20_INTERFACE_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub bInterfaceNumber: u8,
    pub bAlternateSetting: u8,
    pub bNumEndpoints: u8,
    pub bInterfaceClass: u8,
    pub bInterfaceSubClass: u8,
    pub bInterfaceProtocol: u8,
    pub iInterface: u8,
}
unsafe extern "C" {
    pub static LIBUSB20_CONFIG_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_CONFIG_DESC_DECODED {
    pub LIBUSB20_CONFIG_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub wTotalLength: u16,
    pub bNumInterfaces: u8,
    pub bConfigurationValue: u8,
    pub iConfiguration: u8,
    pub bmAttributes: u8,
    pub bMaxPower: u8,
}
unsafe extern "C" {
    pub static LIBUSB20_CONTROL_SETUP_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_CONTROL_SETUP_DECODED {
    pub LIBUSB20_CONTROL_SETUP_FORMAT: *const libusb20_me_format,
    pub bmRequestType: u8,
    pub bRequest: u8,
    pub wValue: u16,
    pub wIndex: u16,
    pub wLength: u16,
}
unsafe extern "C" {
    pub static LIBUSB20_SS_ENDPT_COMP_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_SS_ENDPT_COMP_DESC_DECODED {
    pub LIBUSB20_SS_ENDPT_COMP_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub bMaxBurst: u8,
    pub bmAttributes: u8,
    pub wBytesPerInterval: u16,
}
unsafe extern "C" {
    pub static LIBUSB20_USB_20_DEVCAP_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_USB_20_DEVCAP_DESC_DECODED {
    pub LIBUSB20_USB_20_DEVCAP_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub bDevCapabilityType: u8,
    pub bmAttributes: u32,
}
unsafe extern "C" {
    pub static LIBUSB20_SS_USB_DEVCAP_DESC_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_SS_USB_DEVCAP_DESC_DECODED {
    pub LIBUSB20_SS_USB_DEVCAP_DESC_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub bDevCapabilityType: u8,
    pub bmAttributes: u8,
    pub wSpeedSupported: u16,
    pub bFunctionalitySupport: u8,
    pub bU1DevExitLat: u8,
    pub wU2DevExitLat: u16,
}
unsafe extern "C" {
    pub static LIBUSB20_BOS_DESCRIPTOR_FORMAT: [libusb20_me_format; 1usize];
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIBUSB20_BOS_DESCRIPTOR_DECODED {
    pub LIBUSB20_BOS_DESCRIPTOR_FORMAT: *const libusb20_me_format,
    pub bLength: u8,
    pub bDescriptorType: u8,
    pub wTotalLength: u16,
    pub bNumDeviceCaps: u8,
}
pub const libusb20_class_code_LIBUSB20_CLASS_PER_INTERFACE: libusb20_class_code = 0;
pub const libusb20_class_code_LIBUSB20_CLASS_AUDIO: libusb20_class_code = 1;
pub const libusb20_class_code_LIBUSB20_CLASS_COMM: libusb20_class_code = 2;
pub const libusb20_class_code_LIBUSB20_CLASS_HID: libusb20_class_code = 3;
pub const libusb20_class_code_LIBUSB20_CLASS_PRINTER: libusb20_class_code = 7;
pub const libusb20_class_code_LIBUSB20_CLASS_PTP: libusb20_class_code = 6;
pub const libusb20_class_code_LIBUSB20_CLASS_MASS_STORAGE: libusb20_class_code = 8;
pub const libusb20_class_code_LIBUSB20_CLASS_HUB: libusb20_class_code = 9;
pub const libusb20_class_code_LIBUSB20_CLASS_DATA: libusb20_class_code = 10;
pub const libusb20_class_code_LIBUSB20_CLASS_VENDOR_SPEC: libusb20_class_code = 255;
pub type libusb20_class_code = ::std::os::raw::c_uint;
pub const libusb20_descriptor_type_LIBUSB20_DT_DEVICE: libusb20_descriptor_type = 1;
pub const libusb20_descriptor_type_LIBUSB20_DT_CONFIG: libusb20_descriptor_type = 2;
pub const libusb20_descriptor_type_LIBUSB20_DT_STRING: libusb20_descriptor_type = 3;
pub const libusb20_descriptor_type_LIBUSB20_DT_INTERFACE: libusb20_descriptor_type = 4;
pub const libusb20_descriptor_type_LIBUSB20_DT_ENDPOINT: libusb20_descriptor_type = 5;
pub const libusb20_descriptor_type_LIBUSB20_DT_HID: libusb20_descriptor_type = 33;
pub const libusb20_descriptor_type_LIBUSB20_DT_REPORT: libusb20_descriptor_type = 34;
pub const libusb20_descriptor_type_LIBUSB20_DT_PHYSICAL: libusb20_descriptor_type = 35;
pub const libusb20_descriptor_type_LIBUSB20_DT_HUB: libusb20_descriptor_type = 41;
pub const libusb20_descriptor_type_LIBUSB20_DT_BOS: libusb20_descriptor_type = 15;
pub const libusb20_descriptor_type_LIBUSB20_DT_DEVICE_CAPABILITY: libusb20_descriptor_type = 16;
pub const libusb20_descriptor_type_LIBUSB20_DT_SS_ENDPOINT_COMPANION: libusb20_descriptor_type = 48;
pub type libusb20_descriptor_type = ::std::os::raw::c_uint;
pub const libusb20_device_capability_type_LIBUSB20_WIRELESS_USB_DEVICE_CAPABILITY:
    libusb20_device_capability_type = 1;
pub const libusb20_device_capability_type_LIBUSB20_USB_2_0_EXTENSION_DEVICE_CAPABILITY:
    libusb20_device_capability_type = 2;
pub const libusb20_device_capability_type_LIBUSB20_SS_USB_DEVICE_CAPABILITY:
    libusb20_device_capability_type = 3;
pub const libusb20_device_capability_type_LIBUSB20_CONTAINER_ID_DEVICE_CAPABILITY:
    libusb20_device_capability_type = 4;
pub type libusb20_device_capability_type = ::std::os::raw::c_uint;
pub const libusb20_endpoint_direction_LIBUSB20_ENDPOINT_IN: libusb20_endpoint_direction = 128;
pub const libusb20_endpoint_direction_LIBUSB20_ENDPOINT_OUT: libusb20_endpoint_direction = 0;
pub type libusb20_endpoint_direction = ::std::os::raw::c_uint;
pub const libusb20_transfer_type_LIBUSB20_TRANSFER_TYPE_CONTROL: libusb20_transfer_type = 0;
pub const libusb20_transfer_type_LIBUSB20_TRANSFER_TYPE_ISOCHRONOUS: libusb20_transfer_type = 1;
pub const libusb20_transfer_type_LIBUSB20_TRANSFER_TYPE_BULK: libusb20_transfer_type = 2;
pub const libusb20_transfer_type_LIBUSB20_TRANSFER_TYPE_INTERRUPT: libusb20_transfer_type = 3;
pub type libusb20_transfer_type = ::std::os::raw::c_uint;
pub const libusb20_standard_request_LIBUSB20_REQUEST_GET_STATUS: libusb20_standard_request = 0;
pub const libusb20_standard_request_LIBUSB20_REQUEST_CLEAR_FEATURE: libusb20_standard_request = 1;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_FEATURE: libusb20_standard_request = 3;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_ADDRESS: libusb20_standard_request = 5;
pub const libusb20_standard_request_LIBUSB20_REQUEST_GET_DESCRIPTOR: libusb20_standard_request = 6;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_DESCRIPTOR: libusb20_standard_request = 7;
pub const libusb20_standard_request_LIBUSB20_REQUEST_GET_CONFIGURATION: libusb20_standard_request =
    8;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_CONFIGURATION: libusb20_standard_request =
    9;
pub const libusb20_standard_request_LIBUSB20_REQUEST_GET_INTERFACE: libusb20_standard_request = 10;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_INTERFACE: libusb20_standard_request = 11;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SYNCH_FRAME: libusb20_standard_request = 12;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_SEL: libusb20_standard_request = 48;
pub const libusb20_standard_request_LIBUSB20_REQUEST_SET_ISOCH_DELAY: libusb20_standard_request =
    49;
pub type libusb20_standard_request = ::std::os::raw::c_uint;
pub const libusb20_request_type_LIBUSB20_REQUEST_TYPE_STANDARD: libusb20_request_type = 0;
pub const libusb20_request_type_LIBUSB20_REQUEST_TYPE_CLASS: libusb20_request_type = 32;
pub const libusb20_request_type_LIBUSB20_REQUEST_TYPE_VENDOR: libusb20_request_type = 64;
pub const libusb20_request_type_LIBUSB20_REQUEST_TYPE_RESERVED: libusb20_request_type = 96;
pub type libusb20_request_type = ::std::os::raw::c_uint;
pub const libusb20_request_recipient_LIBUSB20_RECIPIENT_DEVICE: libusb20_request_recipient = 0;
pub const libusb20_request_recipient_LIBUSB20_RECIPIENT_INTERFACE: libusb20_request_recipient = 1;
pub const libusb20_request_recipient_LIBUSB20_RECIPIENT_ENDPOINT: libusb20_request_recipient = 2;
pub const libusb20_request_recipient_LIBUSB20_RECIPIENT_OTHER: libusb20_request_recipient = 3;
pub type libusb20_request_recipient = ::std::os::raw::c_uint;
pub const libusb20_iso_sync_type_LIBUSB20_ISO_SYNC_TYPE_NONE: libusb20_iso_sync_type = 0;
pub const libusb20_iso_sync_type_LIBUSB20_ISO_SYNC_TYPE_ASYNC: libusb20_iso_sync_type = 1;
pub const libusb20_iso_sync_type_LIBUSB20_ISO_SYNC_TYPE_ADAPTIVE: libusb20_iso_sync_type = 2;
pub const libusb20_iso_sync_type_LIBUSB20_ISO_SYNC_TYPE_SYNC: libusb20_iso_sync_type = 3;
pub type libusb20_iso_sync_type = ::std::os::raw::c_uint;
pub const libusb20_iso_usage_type_LIBUSB20_ISO_USAGE_TYPE_DATA: libusb20_iso_usage_type = 0;
pub const libusb20_iso_usage_type_LIBUSB20_ISO_USAGE_TYPE_FEEDBACK: libusb20_iso_usage_type = 1;
pub const libusb20_iso_usage_type_LIBUSB20_ISO_USAGE_TYPE_IMPLICIT: libusb20_iso_usage_type = 2;
pub type libusb20_iso_usage_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_endpoint {
    pub desc: LIBUSB20_ENDPOINT_DESC_DECODED,
    pub extra: libusb20_me_struct,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_interface {
    pub desc: LIBUSB20_INTERFACE_DESC_DECODED,
    pub extra: libusb20_me_struct,
    pub altsetting: *mut libusb20_interface,
    pub endpoints: *mut libusb20_endpoint,
    pub num_altsetting: u8,
    pub num_endpoints: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libusb20_config {
    pub desc: LIBUSB20_CONFIG_DESC_DECODED,
    pub extra: libusb20_me_struct,
    pub interface: *mut libusb20_interface,
    pub num_interface: u8,
}
