[workspace]
resolver = "2"
members = ["crates/ptp-proto", "crates/usb-freebsd", "crates/mtpprobe", "crates/mtpfs"]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.82"
license = "BSD-2-Clause"
repository = "https://github.com/statorit/bsdroid"

[profile.release]
overflow-checks = true
