#!/bin/sh
# Writes the FFI bindings for libfuse version 3.
#
# The repository holds the output in `crates/mtpfs/src/sys.rs`. A user who
# builds the project then needs no `bindgen` and no `libclang`.
#
# Requirements:
#   doas pkg install fusefs-libs3 rust-bindgen-cli
#
# Usage:
#   sh tools/regen-fuse-bindings.sh
set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
out="$repo_root/crates/mtpfs/src/sys.rs"

if ! command -v bindgen >/dev/null 2>&1; then
    echo "regen-fuse-bindings: cannot find bindgen." >&2
    echo "  doas pkg install rust-bindgen-cli" >&2
    exit 2
fi
if [ ! -f /usr/local/include/fuse3/fuse.h ]; then
    echo "regen-fuse-bindings: cannot find fuse3/fuse.h." >&2
    echo "  doas pkg install fusefs-libs3" >&2
    exit 2
fi

wrapper=$(mktemp -t bsdroid_fuse) || exit 2
trap 'rm -f "$wrapper" "$wrapper.h"' EXIT INT TERM
mv "$wrapper" "$wrapper.h"
wrapper="$wrapper.h"
printf '#define FUSE_USE_VERSION 31\n#include <fuse.h>\n' > "$wrapper"

bindgen "$wrapper" \
    --allowlist-function 'fuse_.*' \
    --allowlist-type 'fuse_operations|fuse_file_info|fuse_conn_info|fuse_config|fuse_fill_dir_t|fuse_readdir_flags|fuse_context|fuse_args' \
    --allowlist-var 'FUSE_.*' \
    --default-enum-style consts \
    --no-layout-tests \
    --raw-line '// Generated by tools/regen-fuse-bindings.sh. Do not edit by hand.' \
    --raw-line '#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]' \
    -o "$out" \
    -- -I/usr/local/include/fuse3 -D_FILE_OFFSET_BITS=64

echo "regen-fuse-bindings: write $out"
