#!/bin/sh
# Writes the FFI bindings for libusb20.
#
# The repository holds the output of this script in
# `crates/usb-freebsd/src/sys.rs`. A user who builds the project then needs no
# `bindgen` and no `libclang`.
#
# Run this script only when one of these is true:
#   - FreeBSD changes /usr/include/libusb20.h.
#   - The crate needs a function the allow list does not hold.
#
# Requirements:
#   doas pkg install rust-bindgen-cli
#
# Usage:
#   sh tools/regen-bindings.sh
#   git diff crates/usb-freebsd/src/sys.rs

set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
header=/usr/include/libusb20.h
desc_header=/usr/include/libusb20_desc.h
out="$repo_root/crates/usb-freebsd/src/sys.rs"

for h in "$header" "$desc_header"; do
    if [ ! -f "$h" ]; then
        echo "regen-bindings: cannot find $h." >&2
        echo "  The file comes with the FreeBSD base system." >&2
        exit 2
    fi
done

# libusb20.h declares LIBUSB20_CONTROL_SETUP_DECODED, and libusb20_desc.h
# defines the fields. A wrapper header pulls in both, so the bindings hold the
# fields and not an opaque type.
wrapper=$(mktemp -t bsdroid_wrapper) || exit 2
trap 'rm -f "$wrapper" "$wrapper.h"' EXIT INT TERM
mv "$wrapper" "$wrapper.h"
wrapper="$wrapper.h"
printf '#include <libusb20.h>\n#include <libusb20_desc.h>\n' > "$wrapper"
header=$wrapper

if ! command -v bindgen >/dev/null 2>&1; then
    echo "regen-bindings: cannot find bindgen." >&2
    echo "  doas pkg install rust-bindgen-cli" >&2
    exit 2
fi

echo "regen-bindings: read $header"

bindgen "$header" \
    --allowlist-function 'libusb20_(be|dev|tr)_.*' \
    --allowlist-type 'libusb20_.*|LIBUSB20_.*' \
    --allowlist-var 'LIBUSB20_.*' \
    --default-enum-style consts \
    --no-layout-tests \
    --raw-line '// Generated by tools/regen-bindings.sh. Do not edit by hand.' \
    --raw-line '#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]' \
    -o "$out" \
    -- -I/usr/include

echo "regen-bindings: write $out"
echo "regen-bindings: read the diff before you commit."
